# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [10]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [11]:
A = np.arange(1, 16).reshape(3,5)

print("Dimension of A:", A.ndim)
print("Shape of A:", A.shape)
print("Size of A:", A.size)
print("Datatype of A:", A.dtype)


Dimension of A: 2
Shape of A: (3, 5)
Size of A: 15
Datatype of A: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [13]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matrix B:")
print(B)
print("\nMatrix C:")
print(C)

# Elementwise subtraction
subtraction_result = B - C
print("\nElementwise Subtraction of B and C:")
print(subtraction_result)

# Elementwise multiplication
elementwise_multiplication_result = B * C
print("\nElementwise Multiplication of B and C:")
print(elementwise_multiplication_result)

# Matrix multiplication using @ operator
matrix_multiplication_result = B @ C
print("\nMatrix Multiplication of B and C:")
print(matrix_multiplication_result)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction of B and C:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication of B and C:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication of B and C:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [14]:
B = np.arange(1, 10).reshape(3, 3)
print("Matrix B:")
print(B)

# Exponentiate each number elementwise
B_exp = np.exp(B)
print("\nExponentiated B:")
print(B_exp)

# Minimum value in the whole matrix
min_val = np.min(B)
print("\nMinimum value in B:", min_val)

# Minimum value in each row
min_row = np.min(B, axis=1)
print("\nMinimum value in each row:", min_row)

# Minimum value in each column
min_col = np.min(B, axis=0)
print("\nMinimum value in each column:", min_col)

# Index of minimum value in the matrix
min_index = np.argmin(B)
print("\nIndex of minimum value in B:", min_index)

# Index of minimum value in each row
min_index_row = np.argmin(B, axis=1)
print("\nIndex of minimum value in each row:", min_index_row)

# Sum of all elements
sum_val = np.sum(B)
print("\nSum of all elements in B:", sum_val)

# Mean for each column
mean_col = np.mean(B, axis=0)
print("\nMean for each column:", mean_col)

# Median for each column
median_col = np.median(B, axis=0)
print("\nMedian for each column:", median_col)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiated B:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in B: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of minimum value in B: 0

Index of minimum value in each row: [0 0 0]

Sum of all elements in B: 45

Mean for each column: [4. 5. 6.]

Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [16]:
"""
Only the initial dimensions are addressed when fewer indices than axes are provided during slicing.
The unaddressed latter dimensions are returned in their entirety.
For a 2D matrix like A, when a single index like A[1] is used, a specific row is targeted. 
The entire 1st index row and all columns within that row are selected.
"""

'\nOnly the initial dimensions are addressed when fewer indices than axes are provided during slicing.\nThe unaddressed latter dimensions are returned in their entirety.\nFor a 2D matrix like A, when a single index like A[1] is used, a specific row is targeted. \nThe entire 1st index row and all columns within that row are selected.\n'

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [17]:
"""
It can be used with array A:
for element in A.flat:
    print(element)
"""

'\nIt can be used with array A:\nfor element in A.flat:\n    print(element)\n'

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [18]:
"""
# a = np.arange(30): This creates an array `a` containing numbers from 0 to 29.

# b = a.reshape((2, 3, -1)): This reshapes the array `a` into a new shape with three dimensions.
   - The first dimension has size 2.
   - The second dimension has size 3.
   - The `-1` in the third dimension means that its size should be inferred automatically from the size of `a` and the sizes of the other dimensions.

The resulting shape of `b` is (2, 3, 5).

# print(a): This will print the original flat array of numbers from 0 to 29.

# print(b): This will print the reshaped 3-dimensional array `b`.

When we say `b` has three axes, it means that the array has three dimensions.
- The first axis (dimension) has size 2.
- The second axis has size 3.
- The third axis has size 5.

`b` is two groups (1st axis). Each group contains three sub-groups (2nd axis). Each of these sub-groups contains five elements (3rd axis).
"""

'\n# a = np.arange(30): This creates an array `a` containing numbers from 0 to 29.\n\n# b = a.reshape((2, 3, -1)): This reshapes the array `a` into a new shape with three dimensions.\n   - The first dimension has size 2.\n   - The second dimension has size 3.\n   - The `-1` in the third dimension means that its size should be inferred automatically from the size of `a` and the sizes of the other dimensions.\n\nThe resulting shape of `b` is (2, 3, 5).\n\n# print(a): This will print the original flat array of numbers from 0 to 29.\n\n# print(b): This will print the reshaped 3-dimensional array `b`.\n\nWhen we say `b` has three axes, it means that the array has three dimensions.\n- The first axis (dimension) has size 2.\n- The second axis has size 3.\n- The third axis has size 5.\n\n`b` is two groups (1st axis). Each group contains three sub-groups (2nd axis). Each of these sub-groups contains five elements (3rd axis).\n'

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [19]:

def matrix_operation(matrix1, matrix2, operation):
    # Check if both matrices are ndarrays
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise ValueError("Both inputs should be of type ndarray.")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("For addition, both matrices must have the same shape.")
        return matrix1 + matrix2
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.")
        return matrix1 @ matrix2
    else:
        raise ValueError("Invalid operation specified. Use 'add' or 'multiply'.")

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])

print("A:")
print(A)
print("\nB:")
print(B)
print("\nC:")
print(C)
print("\nD:")
print(D)
print("\nE:")
print(E)

print("\nB - 2A:")
print(matrix_operation(B, 2*A, 'add'))

print("\n3C - E:")
print(matrix_operation(3*C, -E, 'add'))

print("\nAC:")
print(matrix_operation(A, C, 'multiply'))

print("\nCD:")
print(matrix_operation(C, D, 'multiply'))

print("\nCB:")
print(matrix_operation(C, B, 'multiply'))


A:
[[ 2  1 -1]
 [ 1 -1  1]]

B:
[[ 4 -2  1]
 [ 2 -4 -2]]

C:
[[1 2]
 [2 1]]

D:
[[3 4]
 [4 3]]

E:
[[1]
 [2]]

B - 2A:
[[ 8  0 -1]
 [ 4 -6  0]]

3C - E:


ValueError: For addition, both matrices must have the same shape.

**Chap2. Question 2**

In [20]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

# Compute the matrix products
AB = A @ B
AC = A @ C

# Check if AB is equal to AC
product_equal = np.array_equal(AB, AC)

# Check if B is not equal to C
matrices_not_equal = not np.array_equal(B, C)

print("AB:")
print(AB)

print("\nAC:")
print(AC)

print("\nIs AB equal to AC?")
print(product_equal)

print("\nIs B not equal to C?")
print(matrices_not_equal)

AB:
[[ 4  7]
 [ 8 14]]

AC:
[[ 4  7]
 [ 8 14]]

Is AB equal to AC?
True

Is B not equal to C?
True


**Chap2. Question 3**

In [21]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

# Compute AD
AD = A @ D

# Compute DA
DA = D @ A

print("AD:")
print(AD)

print("\nDA:")
print(DA)

AD:
[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA:
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [22]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

product = A @ B
print(product)

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [23]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Compute the inverse of B
B_inv = np.linalg.inv(B)

print("Inverse of A:")
print(A_inv)

print("\nInverse of B:")
print(B_inv)

Inverse of A:
[[ 5. -6.]
 [-4.  5.]]

Inverse of B:
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [24]:
A = np.array([[2, 2], [1, 2]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [25]:
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])

b = np.array([-7, 5, 2])

x = np.linalg.solve(A, b)

print("x1 =", x[0])
print("x2 =", x[1])
print("x3 =", x[2])

x1 = 2.999999999999998
x2 = 3.9999999999999964
x3 = -5.999999999999991


**Chap10. Question 1 b)**

In [26]:
A = np.array([[1, -2, 3],
              [-1, 3, -1],
              [2, -5, 5]])

b = np.array([1, -1, 1])
x = np.linalg.solve(A, b)

print("x1 =", x[0])
print("x2 =", x[1])
print("x3 =", x[2])

x1 = 8.0
x2 = 2.0
x3 = -1.0


**Chap 12. Question 1**

In [27]:
A = np.array([[3, -7, -2],
              [-3, 5, 1],
              [6, -4, 0]])

A_inv = np.linalg.inv(A)

print(A_inv)

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [28]:
# Create an array v1 with values from 0 to 3
v1 = np.arange(4)

# Create v2 as the last two elements of v1
v2 = v1[-2:]

# Print v1 and v2
print("v1:", v1)
print("v2:", v2)

# Check if v1 and v2 are views or copies
print("Is v1 a view? ", v1.base is not None)
print("Is v2 a view? ", v2.base is not None)

# As mentioned, the base attribute of a view returns the original array, 
# while it returns None for a copy. Hence, if v2.base is not None, it's a view.
print("Base of v1:", v1.base)
print("Base of v2:", v2.base)

# Change the last element of v2
v2[-1] = 123

# Print v1 and v2 again to observe the effect of the change on both arrays
print("v1 after change:", v1)
print("v2 after change:", v2)

v1: [0 1 2 3]
v2: [2 3]
Is v1 a view?  False
Is v2 a view?  True
Base of v1: None
Base of v2: [0 1 2 3]
v1 after change: [  0   1   2 123]
v2 after change: [  2 123]
